// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type CartItem struct {
	OwnerID       string
	ProductID     uuid.UUID
	PriceAmount   decimal.Decimal
	PriceCurrency string
	CreatedAt     time.Time
}

type Order struct {
	ID            uuid.UUID
	OwnerID       string
	PriceAmount   decimal.Decimal
	PriceCurrency string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Url           *string
	Tags          []string
	Status        string
	Payload       []byte
	Payloadb      []byte
}

type OrderItem struct {
	OrderID       uuid.UUID
	ProductID     uuid.UUID
	PriceAmount   decimal.Decimal
	PriceCurrency string
	CreatedAt     time.Time
	DeletedAt     *time.Time
}
